import { prisma } from "@/lib/db";
import { NextResponse } from "next/server";
import { requireRole } from "@/lib/authz";
import { logAudit, getClientIp } from "@/lib/audit";
import { readFileSync } from "fs";
import { join } from "path";

interface ParsedMaterial {
  materialName: string;
  lot: string;
  manufacturerMean: number | null;
  manufacturerSD: number | null;
}

interface ParsedRun {
  ca: number;
  date: string; // YYYY-MM-DD
  n1: number | null;
  n2: number | null;
  n3: number | null;
  agent: string | null;
}

interface ParsedAnalyte {
  analyteName: string;
  equipmentName: string;
  materials: ParsedMaterial[];
  runs: ParsedRun[];
}

interface ParsedRunsFile {
  generatedAt: string;
  source: string;
  analytes: ParsedAnalyte[];
}

// POST /api/admin/import-pdf-runs
// Imports historical corridas from prisma/seed-data/parsed-runs.json (generated by
// scripts/parse-pdf-relatorios.js from REVISÃO EM PREPARO PDFs).
// Idempotent: skips runs already present by (analyteMaterialId, date, value).
// Requires ADMIN or SUPERADMIN.
export async function POST(req: Request) {
  const { session, error } = await requireRole(["SUPERADMIN", "ADMIN"]);
  if (error) return error;
  if (!session.user.unitId) {
    return NextResponse.json({ error: "Usuário sem unidade vinculada" }, { status: 400 });
  }

  let data: ParsedRunsFile;
  try {
    const path = join(process.cwd(), "prisma", "seed-data", "parsed-runs.json");
    data = JSON.parse(readFileSync(path, "utf8"));
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    return NextResponse.json({ error: `Arquivo não encontrado: ${msg}` }, { status: 500 });
  }

  const tenantId = session.user.tenantId;
  const unitId = session.user.unitId;
  const userId = session.user.id;

  const summary = {
    analytesProcessed: 0,
    equipmentsCreated: 0,
    materialsCreated: 0,
    analyteMaterialsCreated: 0,
    runsCreated: 0,
    runsSkipped: 0,
    skippedRows: [] as string[],
  };

  for (const entry of data.analytes) {
    summary.analytesProcessed++;

    // ── 1) Equipment ────────────────────────────────────────────────────────
    let equipment = await prisma.equipment.findFirst({
      where: { name: entry.equipmentName, unit: { tenantId } },
      select: { id: true },
    });
    if (!equipment) {
      equipment = await prisma.equipment.create({
        data: { name: entry.equipmentName, unitId },
        select: { id: true },
      });
      summary.equipmentsCreated++;
    }

    // ── 2) Materials (one per lot) ───────────────────────────────────────────
    const materialIds: string[] = [];
    for (const mat of entry.materials) {
      let material = await prisma.material.findFirst({
        where: { name: mat.materialName, lot: mat.lot, unit: { tenantId } },
        select: { id: true },
      });
      if (!material) {
        material = await prisma.material.create({
          data: { name: mat.materialName, lot: mat.lot, unitId },
          select: { id: true },
        });
        summary.materialsCreated++;
      }
      materialIds.push(material.id);
    }

    // ── 3) Analyte (legacy model: one row per equipment) ────────────────────
    // Look for an existing Analyte with this name + equipment within the tenant.
    // If not found, create one using the first material as the legacy materialId.
    let analyte = await prisma.analyte.findFirst({
      where: {
        name: entry.analyteName,
        equipmentId: equipment.id,
        unitRel: { tenantId },
      },
      select: { id: true },
    });

    if (!analyte) {
      const primaryMaterialId = materialIds[0];
      if (!primaryMaterialId) {
        summary.skippedRows.push(`${entry.analyteName}: sem materiais, pulando`);
        continue;
      }
      analyte = await prisma.analyte.create({
        data: {
          unitId,
          equipmentId: equipment.id,
          materialId: primaryMaterialId,
          name: entry.analyteName,
          level: 1,
        },
        select: { id: true },
      });
    }

    // ── 4) AnalyteMaterials (one per material/level) ─────────────────────────
    const amIds: (string | null)[] = [];
    for (let i = 0; i < entry.materials.length; i++) {
      const mat = entry.materials[i];
      const materialId = materialIds[i];
      const level = i + 1;

      let am = await prisma.analyteMaterial.findFirst({
        where: {
          analyteId: analyte.id,
          equipmentId: equipment.id,
          materialId,
          level,
        },
        select: { id: true },
      });

      if (!am) {
        am = await prisma.analyteMaterial.create({
          data: {
            analyteId: analyte.id,
            equipmentId: equipment.id,
            materialId,
            level,
            status: "PRONTO",
            manufacturerMean: mat.manufacturerMean,
            manufacturerSD: mat.manufacturerSD,
          },
          select: { id: true },
        });
        summary.analyteMaterialsCreated++;
      }
      amIds.push(am.id);
    }

    // ── 5) Runs ──────────────────────────────────────────────────────────────
    for (const run of entry.runs) {
      // Each corrida row may have values for N1, N2, N3 levels
      const levelValues: [number, number | null][] = [
        [0, run.n1],
        [1, run.n2],
        [2, run.n3],
      ];

      for (const [idx, value] of levelValues) {
        if (value === null || value === undefined) continue;
        const amId = amIds[idx];
        if (!amId) continue; // No AnalyteMaterial for this level

        // Noon UTC on the run date
        const runAt = new Date(`${run.date}T12:00:00Z`);
        const dayStart = new Date(`${run.date}T00:00:00Z`);
        const dayEnd = new Date(`${run.date}T23:59:59Z`);

        const existing = await prisma.run.findFirst({
          where: {
            analyteMaterialId: amId,
            value,
            runAt: { gte: dayStart, lte: dayEnd },
          },
          select: { id: true },
        });

        if (existing) {
          summary.runsSkipped++;
          continue;
        }

        await prisma.run.create({
          data: {
            analyteId: analyte.id,
            analyteMaterialId: amId,
            equipmentId: equipment.id,
            userId,
            value,
            runAt,
            status: "OK",
            violations: [],
            note: `Importado QualiChart CA ${run.ca}`,
          },
        });
        summary.runsCreated++;
      }
    }
  }

  await logAudit({
    tenantId,
    userId,
    action: "pdf_runs.import",
    entity: "Tenant",
    entityId: tenantId,
    meta: {
      source: data.source,
      generatedAt: data.generatedAt,
      ...summary,
    },
    ip: getClientIp(req),
  });

  return NextResponse.json({
    ok: true,
    summary,
    source: { generatedAt: data.generatedAt, analytes: data.analytes.length },
  });
}
